######################## default configuration ####################
baseURL = "https://docs.capten.ai"
# baseURL = "/"
title = "Capten.AI Docs"
theme = "godocs-4"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disable language
disableLanguages = ["fr"] # disable language from here. example syntax: "fr"

enableGitInfo = true

# hugo outputs
[outputFormats]
[outputFormats.JSON]
  isPlainText = false

[outputFormats.LINKS]
  baseName = 'links'
  isPlainText = true
  mediaType = 'application/json'

[minify]
  disableHTML = true

[outputs]
home = ["HTML", "JSON","LINKS"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

# table of content
[markup.tableOfContents]
startLevel = 0
endLevel = 6
ordered = false

#################### default parameters ################################
[params]
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# feedback form action
feedback_form_action = "#" # contact form works with https://formspree.io
# all doc version
docVersions = []  # Each version should consist of three parts: major version, minor version, and patches. Example of a correct version: ["1.0.0"]. Examples of incorrect versions: ["1.0", "1"].
# current doc version [folder_name]
latestDocVersion = "1.0.1"
# enable/disable Doc Version
docVersion = true
# frequently asked question in homepage
faq = true
# github edit button url
githubEditURL = "https://github.com/intelops/external-docs/tree/main"

# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "GTM-PVRN5BQ"

# seo metadata for OpenGraph / Twitter Card
[params.metadata]
keywords = [
  "Intelops",
  "Capten",
  "Cloud Native",
  "AI",
  "DevOps",
  "DevSecOps",
  "SRE",
  "Kubernetes",
  "Container",
  "Docker",
  "Auto Generate", 
  "Software Supply Chain Security",
  "Engineering Enablement", 
  "Enabling Engineering", 
  "Democratize",
  "Next Gen",
  "Gen AI"
]
description = "Next-Gen Ai based solution to democratize cloud native."
author = "Capten"
image = "images/metadata-images/Capten_logo_full.jpg" # this image will be used as fallback if a page has no image of its own. metadata image.


# logo
[params.logo]
main = "images/new-logos/Capten_logo_full.svg"
favicon = "images/new-logos/new-intelops-fav-icon.png"
main_site_link = "https://capten.ai/"
site_logo = "images/new-logos/Capten Outline Logo Icon.svg" # logo on homepage
docs_logo = "images/docs-logo.png"

# Preloader
[params.preloader]
enable = false
preloader = "images/loader.png" # use jpg, png, svg or gif format.

# Navigation button
[[params.nav_button]]
style = "solid"   # available style: solid, outline
label = "contact"
link = "contact/"


############################# social site ########################
[[params.social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon : https://fontawesome.com/icons
link = "#"

[[params.social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon : https://fontawesome.com/icons
link = "#"

[[params.social]]
title = "github"
icon = "fab fa-github" # fontawesome icon : https://fontawesome.com/icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon : https://fontawesome.com/icons
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
# copyright
copyright = "Outfit Labs, Inc. TX USA"

# banner
[Languages.en.params.banner]
title = "Documentation for Capten.AI projects"
subtitle = "Democratizing Cloud Native Technology. Imaginiation is your Limit!"
image = "images/undraw_homepage_image3.svg"

# feedback
[Languages.en.params.feedback]
title = "Did you find this doc useful?"
content = "Your feedback helps us improve our docs."
positive_placeholder = "What did you like about this doc?"
negative_placeholder = "What can we improve in this doc?"

# call to action
[Languages.en.params.call_to_action]
enable = true
title = "Still Didn't Find Your Answer?"
subtitle = ""
button_label = "Submit a ticket"
button_link = "contact/"
image = "images/undraw_homepage_image4.svg"


############## English navigation ###############
[[Languages.en.menu.footer]]
name = "Contact"
url = "contact/"
weight = 2

[[Languages.en.menu.footer]]
name = "Github"
url = "https://github.com/intelops/"
weight = 3


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 2
# copyright
copyright = "Outfit Labs, Inc. TX USA"

# banner
[Languages.fr.params.banner]
title = "Thème de documentation par l'équipe Themefisher"
subtitle = "Lorem ipsum dolor amet, consetetur sadiffspscing elitr, diam nonumy invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua At."
image = "images/undraw_homepage_image3.svg"

# feedback
[Languages.fr.params.feedback]
title = "Avez-vous trouvé ce document utile?"
content = "Vos commentaires nous aident à améliorer nos documents."
positive_placeholder = "Qu'avez-vous aimé dans ce document?"
negative_placeholder = "Que pouvons-nous améliorer dans ce document?"

# call to action
[Languages.fr.params.call_to_action]
enable = true
title = "Vous n'avez toujours pas trouvé votre réponse?"
image = "images/undraw_homepage_image4.svg"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam <br> nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"

# call to action button
[Languages.fr.params.call_to_action.button]
enable = "true"
label = "Soumettre un ticket"
link = "contact/"


############## French navigation ###############
[[Languages.fr.menu.footer]]
name = "Contact"
url = "contact/"
weight = 2

[[Languages.fr.menu.footer]]
name = "Github"
url = "https://github.com/intelops/"
weight = 3


############################# Plugins ##############################

# CSS Plugin
[[params.plugins.css]]
link = "plugins/featherlight/featherlight.min.css"
[[params.plugins.css]]
link = "plugins/font-awesome/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/regular.css"
[[params.plugins.css]]
link = "plugins/font-awesome/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/icons.css"


# JS Plugin
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
# [[params.plugins.js]]
# link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"
# attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"
[[params.plugins.js]]
link = "plugins/search/auto-complete.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/search/lunr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search-page.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"
[[params.plugins.js]]
link = "plugins/featherlight/featherlight.min.js"
[[params.plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
[[params.plugins.js]]
link = "plugins/scrollmenu/scrollmenu.min.js"

# site variables
[params.variables]
# Color Variables
primary_color = "#F16F33"
text_color = "#1c1e21"
text_color_dark = "#222"
text_color_light = "#999"
body_color = "#fff"
border_color = "#E2E2E2"
black = "#000"
white = "#fff"
light = "#FBFBFB"

# Font Variables
primary_font = "Poppins:wght@300;400;500;600"
primary_font_type = "sans-serif"              # [serif/sans-serif]
secondary_font = ""
secondary_font_type = ""                      # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"
