[build]
  publish = "public"
  command = "yarn build"

[build.environment]
  HUGO_VERSION = "0.118.2"
  GO_VERSION = "1.20.5"

# [[redirects]]
#   from = "/latest/*"
#   to = "/1.0.1/:splat"
#   status = 301
#   force = true

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# below is the permanent redirect from old domain name intelops.ai to new domain name capten.ai
[[redirects]]
  from = "https://intelops-public-docs-prod.netlify.app/"
  to = "https://docs.capten.ai/"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.intelops.ai/*"
  to = "https://docs.capten.ai/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.intelops.ai/"
  to = "https://docs.capten.ai/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.docs.intelops.ai/"
  to = "https://docs.capten.ai/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.docs.intelops.ai/*"
  to = "https://docs.capten.ai/:splat"
  status = 301
  force = true

[[redirects]]
  from = "www.docs.intelops.ai"
  to = "https://docs.capten.ai/"
  status = 301
  force = true

[[redirects]]
  from = "docs.intelops.ai"
  to = "https://docs.capten.ai/"
  status = 301
  force = true
